In [1]:
import pandas as pd

In [3]:
dataset = pd.read_csv("50_startups.csv")

In [4]:
dataset

    R&D Spend  Administartion  Mrketing Spend       State  Profit
0      165616          165754           41479    New York   19683
1      165026          165062           54009  California   17942
2      165192          165584           43133  California   15659
3      165026          165738           51609    New York   19604
4      165264          165011           46877  California   22525
5      165193          165165           43990  California   21121
6      165478          165880           50919  California   24060
7      165732          165208           40310  California   21456
8      165292          165761           54439    New York   20967
9      165480          165878           52484  California   17102
10     165072          165912           41630  California   22923
11     165726          165436           41399  California   15643
12     165079          165271           41943  California   21197
13     165292          165800           51531    New York   16004
14     165263          165378           42778  California   22290
15     165073          165349           52486  California   16551
16     165930          165718           50574    New York   17180

In [9]:
dataset = pd.get_dummies(dataset).astype(int)

In [10]:
dataset

    R&D Spend  Administartion  Mrketing Spend  Profit  State_New York
0      165616          165754           41479   19683               1
1      165026          165062           54009   17942               0
2      165192          165584           43133   15659               0
3      165026          165738           51609   19604               1
4      165264          165011           46877   22525               0
5      165193          165165           43990   21121               0
6      165478          165880           50919   24060               0
7      165732          165208           40310   21456               0
8      165292          165761           54439   20967               1
9      165480          165878           52484   17102               0
10     165072          165912           41630   22923               0
11     165726          165436           41399   15643               0
12     165079          165271           41943   21197               0
13     165292          165800           51531   16004               1
14     165263          165378           42778   22290               0
15     165073          165349           52486   16551               0
16     165930          165718           50574   17180               1

In [11]:
dataset.columns

Index(['R&D Spend', 'Administartion', 'Mrketing Spend', 'Profit',
       'State_New York'],
      dtype='object')

In [14]:
independent = dataset[['R&D Spend', 'Administartion', 'Mrketing Spend',
       'State_New York']]

In [15]:
independent

    R&D Spend  Administartion  Mrketing Spend  State_New York
0      165616          165754           41479               1
1      165026          165062           54009               0
2      165192          165584           43133               0
3      165026          165738           51609               1
4      165264          165011           46877               0
5      165193          165165           43990               0
6      165478          165880           50919               0
7      165732          165208           40310               0
8      165292          165761           54439               1
9      165480          165878           52484               0
10     165072          165912           41630               0
11     165726          165436           41399               0
12     165079          165271           41943               0
13     165292          165800           51531               1
14     165263          165378           42778               0
15     165073          165349           52486               0
16     165930          165718           50574               1

In [16]:
dependent = dataset[['Profit']]

In [17]:
dependent

    Profit
0    19683
1    17942
2    15659
3    19604
4    22525
5    21121
6    24060
7    21456
8    20967
9    17102
10   22923
11   15643
12   21197
13   16004
14   22290
15   16551
16   17180

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent,test_size=0.30,random_state=0)

In [35]:
X_train

    R&D Spend  Administartion  Mrketing Spend  State_New York
2      165192          165584           43133               0
14     165263          165378           42778               0
10     165072          165912           41630               0
7      165732          165208           40310               0
16     165930          165718           50574               1
11     165726          165436           41399               0
3      165026          165738           51609               1
0      165616          165754           41479               1
5      165193          165165           43990               0
15     165073          165349           52486               0
12     165079          165271           41943               0

In [36]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [37]:
X_train

array([[-0.51841513,  0.34410509, -0.35343364, -0.61237244],
       [-0.29222395, -0.51181382, -0.43525474, -0.61237244],
       [-0.90071009,  1.70692742, -0.69984806, -0.61237244],
       [ 1.20191218, -1.21815466, -1.00408427, -0.61237244],
       [ 1.83269886,  0.90086787,  1.36158277,  1.63299316],
       [ 1.18279743, -0.27082694, -0.75308939, -0.61237244],
       [-1.04725649,  0.98396679,  1.60013162,  1.63299316],
       [ 0.83236039,  1.05044593, -0.73465083,  1.63299316],
       [-0.51522934, -1.39681735, -0.15591058, -0.61237244],
       [-0.8975243 , -0.63230726,  1.80226432, -0.61237244],
       [-0.87840955, -0.95639306, -0.6277072 , -0.61237244]])

In [93]:
from sklearn.svm import SVR
regressor=SVR(kernel="poly", C=1000)
regressor.fit(X_train,Y_train)

C:\Users\acer\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1000, kernel='poly')

In [94]:
regressor.interce

AttributeError: 'SVR' object has no attribute 'interce'

In [95]:
regressor.n_support_

array([11], dtype=int32)

In [96]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)

In [97]:
y_pred=regressor.predict(X_test)

In [101]:
from sklearn.metrics import r2_score
r2_score=r2_score(Y_test,y_pred)
r2_score

0.21496746287062163

In [99]:
r2_score

0.21496746287062163

In [100]:
import pickle 
filename="finalized_model_svm.sav"

In [28]:
pickle.dump(regressor,open(filename,'wb'))