In [1]:
import pandas as pd

In [4]:
dataset= pd.read_csv("50_startups.csv")

In [5]:
dataset

    R&D Spend  Administartion  Mrketing Spend       State  Profit
0      165616          165754           41479    New York   19683
1      165026          165062           54009  California   17942
2      165192          165584           43133  California   15659
3      165026          165738           51609    New York   19604
4      165264          165011           46877  California   22525
5      165193          165165           43990  California   21121
6      165478          165880           50919  California   24060
7      165732          165208           40310  California   21456
8      165292          165761           54439    New York   20967
9      165480          165878           52484  California   17102
10     165072          165912           41630  California   22923
11     165726          165436           41399  California   15643
12     165079          165271           41943  California   21197
13     165292          165800           51531    New York   16004
14     165263          165378           42778  California   22290
15     165073          165349           52486  California   16551
16     165930          165718           50574    New York   17180

In [6]:
dataset = pd.get_dummies(dataset).astype(int)

In [7]:
dataset

,R&D Spend,Administartion,Mrketing Spend,Profit,State_California,State_New York
0,165616,165754,41479,19683,0,1
1,165026,165062,54009,17942,1,0
2,165192,165584,43133,15659,1,0
3,165026,165738,51609,19604,0,1
4,165264,165011,46877,22525,1,0
5,165193,165165,43990,21121,1,0
6,165478,165880,50919,24060,1,0
7,165732,165208,40310,21456,1,0
8,165292,165761,54439,20967,0,1
9,165480,165878,52484,17102,1,0
10,165072,165912,41630,22923,1,0
11,165726,165436,41399,15643,1,0
12,165079,165271,41943,21197,1,0
13,165292,165800,51531,16004,0,1
14,165263,165378,42778,22290,1,0
15,165073,165349,52486,16551,1,0
16,165930,165718,50574,17180,0,1

In [8]:
dataset.columns

Index(['R&D Spend', 'Administartion', 'Mrketing Spend', 'Profit',
       'State_California', 'State_New York'],
      dtype='object')

In [9]:
independent = dataset[['R&D Spend', 'Administartion', 'Mrketing Spend',
       'State_New York']]

In [10]:
independent

    R&D Spend  Administartion  Mrketing Spend  State_New York
0      165616          165754           41479               1
1      165026          165062           54009               0
2      165192          165584           43133               0
3      165026          165738           51609               1
4      165264          165011           46877               0
5      165193          165165           43990               0
6      165478          165880           50919               0
7      165732          165208           40310               0
8      165292          165761           54439               1
9      165480          165878           52484               0
10     165072          165912           41630               0
11     165726          165436           41399               0
12     165079          165271           41943               0
13     165292          165800           51531               1
14     165263          165378           42778               0
15     165073          165349           52486               0
16     165930          165718           50574               1

In [43]:
dependent = dataset[['Profit']]

In [44]:
dependent

    Profit
0    19683
1    17942
2    15659
3    19604
4    22525
5    21121
6    24060
7    21456
8    20967
9    17102
10   22923
11   15643
12   21197
13   16004
14   22290
15   16551
16   17180

In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent,test_size=0.30,random_state=0)

In [46]:
X_train

    R&D Spend  Administartion  Mrketing Spend  State_New York
2      165192          165584           43133               0
14     165263          165378           42778               0
10     165072          165912           41630               0
7      165732          165208           40310               0
16     165930          165718           50574               1
11     165726          165436           41399               0
3      165026          165738           51609               1
0      165616          165754           41479               1
5      165193          165165           43990               0
15     165073          165349           52486               0
12     165079          165271           41943               0

In [47]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=1000,criterion='squared_error', random_state = 1.0)
regressor.fit(X_train,Y_train)

C:\Users\acer\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor(n_estimators=1000, random_state=0)

In [48]:
y_pred=regressor.predict(X_test)

In [49]:
from sklearn.metrics import r2_score
r2_score=r2_score(Y_test,y_pred)
r2_score

0.10546163644665951

In [50]:
r2_score

0.10546163644665951

In [51]:
import pickle 
filename="finalized_model_random_forest.sav"

In [52]:
pickle.dump(regressor,open(filename,'wb'))

In [54]:
loaded_model=pickle.load(open("finalized_model_random_forest.sav",'rb'))
result=loaded_model.predict([[1234,343,5432,1]])

C:\Users\acer\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

In [55]:
result

array([20579.102])